/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPortfolioRouteImport } from './routes/_app.portfolio'
import { Route as AppMarketRouteImport } from './routes/_app.market'
import { Route as AppLeaderboardRouteImport } from './routes/_app.leaderboard'
import { Route as AppFinancesRouteImport } from './routes/_app.finances'
import { Route as ApiPublicHooksWeatherUpdateRouteImport } from './routes/api/public/hooks/weather-update'
import { Route as ApiPublicHooksLeaderboardRefreshRouteImport } from './routes/api/public/hooks/leaderboard-refresh'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketRoute = AppMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancesRoute = AppFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicHooksWeatherUpdateRoute =
  ApiPublicHooksWeatherUpdateRouteImport.update({
    id: '/api/public/hooks/weather-update',
    path: '/api/public/hooks/weather-update',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksLeaderboardRefreshRoute =
  ApiPublicHooksLeaderboardRefreshRouteImport.update({
    id: '/api/public/hooks/leaderboard-refresh',
    path: '/api/public/hooks/leaderboard-refresh',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/finances': typeof AppFinancesRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/market': typeof AppMarketRoute
  '/portfolio': typeof AppPortfolioRoute
  '/profile': typeof AppProfileRoute
  '/api/public/hooks/leaderboard-refresh': typeof ApiPublicHooksLeaderboardRefreshRoute
  '/api/public/hooks/weather-update': typeof ApiPublicHooksWeatherUpdateRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/finances': typeof AppFinancesRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/market': typeof AppMarketRoute
  '/portfolio': typeof AppPortfolioRoute
  '/profile': typeof AppProfileRoute
  '/': typeof AppIndexRoute
  '/api/public/hooks/leaderboard-refresh': typeof ApiPublicHooksLeaderboardRefreshRoute
  '/api/public/hooks/weather-update': typeof ApiPublicHooksWeatherUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/finances': typeof AppFinancesRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/market': typeof AppMarketRoute
  '/_app/portfolio': typeof AppPortfolioRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/': typeof AppIndexRoute
  '/api/public/hooks/leaderboard-refresh': typeof ApiPublicHooksLeaderboardRefreshRoute
  '/api/public/hooks/weather-update': typeof ApiPublicHooksWeatherUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/finances'
    | '/leaderboard'
    | '/market'
    | '/portfolio'
    | '/profile'
    | '/api/public/hooks/leaderboard-refresh'
    | '/api/public/hooks/weather-update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/finances'
    | '/leaderboard'
    | '/market'
    | '/portfolio'
    | '/profile'
    | '/'
    | '/api/public/hooks/leaderboard-refresh'
    | '/api/public/hooks/weather-update'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/finances'
    | '/_app/leaderboard'
    | '/_app/market'
    | '/_app/portfolio'
    | '/_app/profile'
    | '/_app/'
    | '/api/public/hooks/leaderboard-refresh'
    | '/api/public/hooks/weather-update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicHooksLeaderboardRefreshRoute: typeof ApiPublicHooksLeaderboardRefreshRoute
  ApiPublicHooksWeatherUpdateRoute: typeof ApiPublicHooksWeatherUpdateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolio': {
      id: '/_app/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/market': {
      id: '/_app/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AppMarketRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finances': {
      id: '/_app/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof AppFinancesRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hooks/weather-update': {
      id: '/api/public/hooks/weather-update'
      path: '/api/public/hooks/weather-update'
      fullPath: '/api/public/hooks/weather-update'
      preLoaderRoute: typeof ApiPublicHooksWeatherUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/leaderboard-refresh': {
      id: '/api/public/hooks/leaderboard-refresh'
      path: '/api/public/hooks/leaderboard-refresh'
      fullPath: '/api/public/hooks/leaderboard-refresh'
      preLoaderRoute: typeof ApiPublicHooksLeaderboardRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppFinancesRoute: typeof AppFinancesRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppMarketRoute: typeof AppMarketRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFinancesRoute: AppFinancesRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppMarketRoute: AppMarketRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicHooksLeaderboardRefreshRoute: ApiPublicHooksLeaderboardRefreshRoute,
  ApiPublicHooksWeatherUpdateRoute: ApiPublicHooksWeatherUpdateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
